/**
 * VAIMA Semantic Indexing Ingestion Pipeline
 * Transfers safety manual documents from db.json into the ChromaDB vector database.
 */
const fs = require('fs');
const path = require('path');
const { getSafetyCollection } = require('./vectorStore');

async function runIngestion() {
  console.log("🚀 Starting database to vector store ingestion process...");

  // Path lookup for root db.json (one directory level up relative to chroma-migration)
  const dbPath = path.resolve(__dirname, '..', 'db.json');
  if (!fs.existsSync(dbPath)) {
    console.error("❌ Error: Could not locate 'db.json' at root path:", dbPath);
    process.exit(1);
  }

  try {
    const rawData = fs.readFileSync(dbPath, 'utf8');
    const db = JSON.parse(rawData);

    if (!db.documents || !Array.isArray(db.documents)) {
      console.error("❌ Error: 'documents' collection in db.json is missing or not a valid array.");
      process.exit(1);
    }

    // Filter out empty or dynamic mock documents
    const docs = db.documents.filter(d => d.content && d.content.trim().length > 3);
    if (docs.length === 0) {
      console.log("⚠️ No valid safety handbook documents available for semantic indexing.");
      return;
    }

    console.log(`🔍 Found ${docs.length} valid safety handbook documents for ingestion.`);

    // Retrieve active safety manuals collection from Chroma
    const collection = await getSafetyCollection();

    // Prepare arrays for Chroma batch insert
    const ids = [];
    const metadatas = [];
    const documents = [];

    docs.forEach(doc => {
      ids.push(doc.id);
      metadatas.push({
        title: doc.title || "Safety Guideline",
        fileName: doc.fileName || "N/A",
        accessLevel: doc.accessLevel || "OPERATOR",
        uploadedBy: doc.uploadedBy || "System Admin",
        uploadedAt: doc.uploadedAt || new Date().toISOString()
      });
      documents.push(doc.content);
    });

    console.log("⚡ Adding text documents with autogenerated server-side embeddings to safety_manuals collection...");
    
    // Perform bulk insertion into ChromaDB collection
    await collection.add({
      ids: ids,
      metadatas: metadatas,
      documents: documents
    });

    console.log("✅ Ingestion successfully completed! Manuals are now semantically indexable in ChromaDB.");
  } catch (error) {
    console.error("❌ Ingestion crashed during file parsing or vector serialization:", error);
  }
}

// Check if run directly
if (require.main === module) {
  runIngestion();
}

module.exports = { runIngestion };
